app/api/auth/me/route.ts, app/api/auth/set-token/route.ts, app/api/chat/route.ts, app/auth/callback/page.tsx, app/components/LoginOverlay.tsx, app/page.tsx, app/store/authStore.ts, package.json, pnpm-lock.yaml
Adds auth similarly to writing/project-zeno-frontend, adapted to Next.js pages
=> add auth dialog

app/components/MapAreaControls.tsx, app/store/drawAreaSlice.ts, app/store/uploadAreaSlice.ts
Contributes to #24.
Changes:
- Mouse pointer changes from crosshair to default on draw finish
- Add close button to ValidationErrorDisplay
- Hide SelectionModeDisplay on upload dialog close
This is ready to review.
=> Draw fixes

app/components/ChatInput.tsx, app/components/LoginOverlay.tsx, app/layout.tsx, app/page.tsx, app/threads/[id]/page.tsx
This pr:
- Adds user email to header
- Swaps project brand names
=> Add user email header, swap project brand name

.env.example, .gitignore, README.md, app/components/Map.tsx
Changes:
- Update README with more detailed instructions on how to run the app
- Remove hardcoded mapbox access token
@kamicut do you know if the access token introduced [here](https://github.com/wri/project-zeno-next/commit/ee4e146e4828922b7d5a59ab4a6f8ed5914e55e4#diff-80c5088e3697f847c3f249b4121e79967f310d980b3761d1cf4f38d9a35875caR76-R77) has origin restrictions? If not we might need to rotate them to avoid abuse.
This is ready for review.
=> Update README, remove hardcoded token

app/api/shared/parse-stream-message.ts, app/components/map/layers/SelectAreaLayer.tsx, app/store/drawAreaSlice.ts, app/types/map.ts, app/utils/areaHelpers.ts
=> fix for build errors

.github/workflows/ci.yml, package.json
Changes:
- Run `pnpm lint` and `pnpm build` on non-draft PRs to ensure the app is deployable
- Update pnpm version
=> feat: add PR checks

app/components/map/layers/CustomAreasLayer.tsx, app/store/drawAreaSlice.ts
Needed to get custom areas to work in the chat as part of https://github.com/wri/project-zeno/pull/297
=> Update custom area type to be consistent with other types

README.md, app/components/ChatInput.tsx, app/components/LoginOverlay.tsx, app/components/PageHeader.tsx, app/components/WelcomeModal.tsx, app/layout.tsx, app/store/chatStore.ts
Small cosmetic tweak to the intro text and update to GNW
=> Update initial message message text

app/ChatPanelHeader.tsx, app/components/MessageBubble.tsx, app/components/WidgetMessage.tsx
Jump to insight dropdown. Contributes to https://github.com/wri/project-zeno-next/issues/67
See [designs](https://www.figma.com/design/N20cpSWt9kWZWILQOcsdIT/WRI_LCL_ProjectZeno?node-id=2243-2290&t=z9fxtkUFdt7baH6S-4).
WIP - starting with a simple implementation.
Todo:
=> Go-to Insights dropdown

app/ChatPanelHeader.tsx, app/components/ThreadActionsMenu.tsx, app/components/ThreadDeleteDialog.tsx, app/components/ThreadRenameDialog.tsx, app/sidebar.tsx
Refactor to reuse thread action menu and dialogs.
=> Refactor thread action menus and dialogs

app/components/MessageBubble.tsx, pnpm-lock.yaml
Contributes to #39.
https://github.com/user-attachments/assets/0b299a5f-a100-4251-9b12-0265846369a5
=> Copy message response

amplify.yml
Adds an amplify.yml that's needed for Amplify to be able to deploy the app.
cc @kamicut @danielfdsilva
=> Amplify config

app/api/chat/route.ts, app/api/proxy/[...path]/route.ts, app/api/shared/utils.ts, app/api/threads/[id]/route.ts, app/api/threads/route.ts, app/components/LoginOverlay.tsx, app/store/authStore.ts, middleware.ts
Initial code for anonymous access. Needs to be fully tested once the api is ready.
The secret api key should be set using `NEXT_SERVICE_API_KEY` env.
=> Allow anonymous users to browse the app

app/api/chat/route.ts
There as some refactoring to simplify the logic!
=> Handle missing timestamp in langchain message

app/components/PageHeader.tsx
Adds a beta badge to the header
See [designs](https://www.figma.com/design/N20cpSWt9kWZWILQOcsdIT/WRI_LCL_ProjectZeno?node-id=1830-9574&t=Ptsi2DvEPLIpL4tY-4)
=> Add beta badge

app/dashboard/page.tsx
Stubs user profile page for  connection to API.
=> Stub user info page

app/components/HotjarTrigger.tsx, app/layout.tsx
Adds a simple hotjar survey trigger on abandon page.
=> Add hotjar event trigger

app/(home)/sections/5_SupportWorkTabs.tsx, app/components/GlobalHeader.tsx
Minor styles to add to #262 
Wrapper for "Support your work" section:
Wrap global nav items, and close mobile nav drawer on item click
https://github.com/user-attachments/assets/3fa47d4d-2c85-4130-91c7-31485b7248f9
=> Update / landing styles polish

app/api/auth/logout/route.ts, app/components/PageHeader.tsx, app/dashboard/page.tsx, app/sidebar.tsx
Uses the new logout mechanism with the callback url to logout and redirect to '/'
@LanesGood I add toasts to indicate logout
=> logout through RW

app/constants/datasets.ts, public/welcome-prompts.json
=> merge to main

app/components/ContextMenu.tsx, app/components/MessageBubble.tsx
- Adds a manual area select trigger
- Update response feedback triggers to be distinct
=> Update ga triggers
